import { Property, PropertyStats, RecentInquiry, Province, PropertyType, PropertyStatus, ListingType } from '@/types/property';

// Helper function to generate IDs
const generateId = () => Math.random().toString(36).substring(2, 15);

// Sample property images
const sampleImages = [
  {
    id: generateId(),
    url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=200&q=80',
    caption: 'Front view',
    isPrimary: true,
    order: 0,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=200&q=80',
    caption: 'Living room',
    isPrimary: false,
    order: 1,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=200&q=80',
    caption: 'Kitchen',
    isPrimary: false,
    order: 2,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=200&q=80',
    caption: 'Backyard with pool',
    isPrimary: false,
    order: 3,
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    url: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&q=80',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=200&q=80',
    caption: 'Master bedroom',
    isPrimary: false,
    order: 4,
    createdAt: new Date().toISOString(),
  },
];

// Sample agent
const sampleAgent = {
  id: generateId(),
  name: 'Sarah Mitchell',
  email: 'sarah@propagent.co.za',
  phone: '+27 82 555 0123',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80',
  agencyName: 'PropAgent Premium',
  agencyLogo: '/logo.png',
};

// Generate sample properties
export const sampleProperties: Property[] = [
  {
    id: generateId(),
    title: 'Modern 4-Bedroom Family Home in Sandton',
    description: 'Stunning contemporary home featuring open-plan living spaces, gourmet kitchen with granite tops, and a private garden with swimming pool. Perfect for entertaining with a covered patio and built-in braai. Close to top schools and shopping centers.',
    listingType: 'sale' as ListingType,
    type: 'house' as PropertyType,
    status: 'active' as PropertyStatus,
    location: {
      streetAddress: '15 Oak Lane',
      suburb: 'Sandton',
      city: 'Johannesburg',
      province: 'gauteng' as Province,
      postalCode: '2196',
      latitude: -26.1091,
      longitude: 28.0576,
      complexName: 'The Oaks Estate',
    },
    pricing: {
      price: 8500000,
      negotiable: true,
      levies: 0,
      ratesAndTaxes: 4500,
      transferDuty: 850000,
      bondRegistration: 25000,
    },
    specs: {
      bedrooms: 4,
      bathrooms: 3.5,
      garages: 2,
      carports: 2,
      totalParking: 4,
      erfSize: 850,
      floorSize: 420,
      yearBuilt: 2019,
    },
    features: {
      pool: true,
      garden: true,
      securitySystem: true,
      borehole: false,
      solarPanels: true,
      backupPower: true,
      airConditioning: true,
      furnished: false,
      petFriendly: true,
      wheelchairAccess: false,
      balcony: false,
      fireplace: true,
      staffQuarters: true,
      flatlet: false,
      tennisCourt: false,
      gym: false,
      elevator: false,
    },
    images: sampleImages,
    agent: sampleAgent,
    createdAt: '2026-03-15T10:30:00Z',
    updatedAt: '2026-04-01T14:22:00Z',
    publishedAt: '2026-03-15T12:00:00Z',
    viewCount: 1247,
    inquiryCount: 18,
    favoriteCount: 89,
    syndicatedTo: ['Property24', 'Private Property', 'Gumtree'],
    slug: 'modern-4-bedroom-family-home-sandton',
    metaTitle: 'Modern 4-Bedroom Family Home in Sandton | PropAgent',
    metaDescription: 'Stunning contemporary home in Sandton featuring open-plan living, gourmet kitchen, private garden with pool. 4 bed, 3.5 bath, R8.5M.',
    isDraft: false,
  },
  {
    id: generateId(),
    title: 'Luxury Apartment with Sea Views in Camps Bay',
    description: 'Exclusive beachfront apartment offering breathtaking Atlantic Ocean views. Features floor-to-ceiling windows, designer finishes, and access to a communal infinity pool. Walking distance to Camps Bay beach and trendy restaurants.',
    listingType: 'sale' as ListingType,
    type: 'apartment' as PropertyType,
    status: 'active' as PropertyStatus,
    location: {
      streetAddress: '42 Victoria Road',
      suburb: 'Camps Bay',
      city: 'Cape Town',
      province: 'western_cape' as Province,
      postalCode: '8005',
      latitude: -33.9507,
      longitude: 18.3774,
      unitNumber: 'Penthouse 1',
    },
    pricing: {
      price: 18500000,
      negotiable: false,
      levies: 8500,
      ratesAndTaxes: 7200,
    },
    specs: {
      bedrooms: 3,
      bathrooms: 3,
      garages: 2,
      floorSize: 280,
      yearBuilt: 2021,
    },
    features: {
      pool: true,
      garden: false,
      securitySystem: true,
      borehole: false,
      solarPanels: false,
      backupPower: true,
      airConditioning: true,
      furnished: true,
      petFriendly: false,
      wheelchairAccess: true,
      balcony: true,
      fireplace: false,
      staffQuarters: false,
      flatlet: false,
      tennisCourt: false,
      gym: true,
      elevator: true,
    },
    images: [
      {
        id: generateId(),
        url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=200&q=80',
        isPrimary: true,
        order: 0,
        createdAt: new Date().toISOString(),
      },
      {
        id: generateId(),
        url: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=200&q=80',
        isPrimary: false,
        order: 1,
        createdAt: new Date().toISOString(),
      },
    ],
    agent: sampleAgent,
    createdAt: '2026-03-20T09:15:00Z',
    updatedAt: '2026-04-02T16:45:00Z',
    publishedAt: '2026-03-20T10:00:00Z',
    viewCount: 2156,
    inquiryCount: 32,
    favoriteCount: 156,
    syndicatedTo: ['Property24', 'Private Property'],
    slug: 'luxury-apartment-sea-views-camps-bay',
    metaTitle: 'Luxury Sea View Apartment Camps Bay | PropAgent',
    metaDescription: 'Exclusive beachfront penthouse with Atlantic Ocean views. 3 bed, 3 bath, R18.5M. Designer finishes, infinity pool access.',
    isDraft: false,
  },
  {
    id: generateId(),
    title: 'Spacious Townhouse in Umhlanga Ridge',
    description: 'Beautiful modern townhouse in a secure estate. Open-plan kitchen and living area leading to a private garden. Complex offers 24-hour security, clubhouse, and swimming pool. Close to Gateway Theatre of Shopping and Umhlanga Beach.',
    listingType: 'rent' as ListingType,
    type: 'townhouse' as PropertyType,
    status: 'active' as PropertyStatus,
    location: {
      streetAddress: '88 Ridge Boulevard',
      suburb: 'Umhlanga Ridge',
      city: 'Durban',
      province: 'kwazulu_natal' as Province,
      postalCode: '4319',
      latitude: -29.7251,
      longitude: 31.0661,
      complexName: 'Ridge View Estate',
    },
    pricing: {
      price: 28500,
      negotiable: false,
      depositRequired: 28500,
      depositMonths: 1,
    },
    specs: {
      bedrooms: 3,
      bathrooms: 2.5,
      garages: 2,
      erfSize: 350,
      floorSize: 220,
      yearBuilt: 2018,
    },
    features: {
      pool: true,
      garden: true,
      securitySystem: true,
      borehole: false,
      solarPanels: false,
      backupPower: false,
      airConditioning: true,
      furnished: false,
      petFriendly: true,
      wheelchairAccess: false,
      balcony: true,
      fireplace: false,
      staffQuarters: false,
      flatlet: false,
      tennisCourt: false,
      gym: true,
      elevator: false,
    },
    images: [
      {
        id: generateId(),
        url: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=200&q=80',
        isPrimary: true,
        order: 0,
        createdAt: new Date().toISOString(),
      },
    ],
    agent: sampleAgent,
    createdAt: '2026-03-25T11:00:00Z',
    updatedAt: '2026-04-03T09:30:00Z',
    publishedAt: '2026-03-25T11:30:00Z',
    viewCount: 892,
    inquiryCount: 14,
    favoriteCount: 45,
    syndicatedTo: ['Property24', 'Private Property'],
    slug: 'spacious-townhouse-umhlanga-ridge',
    metaTitle: '3-Bed Townhouse for Rent Umhlanga Ridge | PropAgent',
    metaDescription: 'Modern townhouse in secure estate near Gateway. 3 bed, 2.5 bath, R28,500/month. 24hr security, pool, gym access.',
    isDraft: false,
  },
  {
    id: generateId(),
    title: 'Executive Home in Waterkloof Ridge',
    description: 'Magnificent double-storey residence on a corner stand with exceptional finishes. Features include a wine cellar, cinema room, and separate cottage. Landscaped garden with heated pool. Prime location in prestigious Waterkloof Ridge.',
    listingType: 'sale' as ListingType,
    type: 'house' as PropertyType,
    status: 'active' as PropertyStatus,
    location: {
      streetAddress: '127 Bronberg Street',
      suburb: 'Waterkloof Ridge',
      city: 'Pretoria',
      province: 'gauteng' as Province,
      postalCode: '0181',
      latitude: -25.8092,
      longitude: 28.2523,
    },
    pricing: {
      price: 12500000,
      negotiable: true,
      ratesAndTaxes: 5800,
    },
    specs: {
      bedrooms: 5,
      bathrooms: 4.5,
      garages: 3,
      carports: 2,
      totalParking: 5,
      erfSize: 1200,
      floorSize: 650,
      yearBuilt: 2016,
    },
    features: {
      pool: true,
      garden: true,
      securitySystem: true,
      borehole: true,
      solarPanels: true,
      backupPower: true,
      airConditioning: true,
      furnished: false,
      petFriendly: true,
      wheelchairAccess: false,
      balcony: true,
      fireplace: true,
      staffQuarters: true,
      flatlet: true,
      tennisCourt: true,
      gym: true,
      elevator: false,
    },
    images: [
      {
        id: generateId(),
        url: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=200&q=80',
        isPrimary: true,
        order: 0,
        createdAt: new Date().toISOString(),
      },
    ],
    agent: sampleAgent,
    createdAt: '2026-03-10T14:20:00Z',
    updatedAt: '2026-04-01T10:15:00Z',
    publishedAt: '2026-03-10T15:00:00Z',
    viewCount: 1876,
    inquiryCount: 28,
    favoriteCount: 134,
    syndicatedTo: ['Property24', 'Private Property', 'Gumtree', 'OLX'],
    slug: 'executive-home-waterkloof-ridge',
    metaTitle: '5-Bed Executive Home Waterkloof Ridge | PropAgent',
    metaDescription: 'Magnificent double-storey home with wine cellar, cinema, cottage. 5 bed, 4.5 bath, tennis court, heated pool. R12.5M.',
    isDraft: false,
  },
  {
    id: generateId(),
    title: 'Modern Studio Apartment in Rosebank',
    description: 'Contemporary studio apartment perfect for young professionals. Features include a Juliet balcony, modern kitchenette, and built-in cupboards. Walking distance to Rosebank Mall and Gautrain station.',
    listingType: 'rent' as ListingType,
    type: 'apartment' as PropertyType,
    status: 'pending' as PropertyStatus,
    location: {
      streetAddress: '45 Jellicoe Avenue',
      suburb: 'Rosebank',
      city: 'Johannesburg',
      province: 'gauteng' as Province,
      postalCode: '2196',
      unitNumber: 'Unit 412',
      complexName: 'The Vantage',
    },
    pricing: {
      price: 9800,
      negotiable: false,
      depositRequired: 19600,
      depositMonths: 2,
    },
    specs: {
      bedrooms: 1,
      bathrooms: 1,
      garages: 0,
      floorSize: 45,
      yearBuilt: 2020,
    },
    features: {
      pool: true,
      garden: false,
      securitySystem: true,
      borehole: false,
      solarPanels: false,
      backupPower: false,
      airConditioning: true,
      furnished: true,
      petFriendly: false,
      wheelchairAccess: true,
      balcony: true,
      fireplace: false,
      staffQuarters: false,
      flatlet: false,
      tennisCourt: false,
      gym: true,
      elevator: true,
    },
    images: [
      {
        id: generateId(),
        url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=200&q=80',
        isPrimary: true,
        order: 0,
        createdAt: new Date().toISOString(),
      },
    ],
    agent: sampleAgent,
    createdAt: '2026-03-28T08:45:00Z',
    updatedAt: '2026-04-05T13:20:00Z',
    publishedAt: '2026-03-28T09:00:00Z',
    viewCount: 567,
    inquiryCount: 12,
    favoriteCount: 28,
    syndicatedTo: ['Property24', 'Private Property'],
    slug: 'modern-studio-apartment-rosebank',
    metaTitle: 'Studio Apartment for Rent Rosebank | PropAgent',
    metaDescription: 'Contemporary furnished studio near Rosebank Mall & Gautrain. 1 bed, 1 bath, R9,800/month. Pool, gym access.',
    isDraft: false,
  },
  {
    id: generateId(),
    title: 'Charming 3-Bedroom House in Claremont',
    description: 'Beautiful character home with original Oregon pine floors and high ceilings. Large established garden with mature trees. Close to Cavendish Square and excellent schools. Ideal family home.',
    listingType: 'sale' as ListingType,
    type: 'house' as PropertyType,
    status: 'sold' as PropertyStatus,
    location: {
      streetAddress: '23 Protea Road',
      suburb: 'Claremont',
      city: 'Cape Town',
      province: 'western_cape' as Province,
      postalCode: '7708',
      latitude: -33.9785,
      longitude: 18.4655,
    },
    pricing: {
      price: 6200000,
      negotiable: false,
      ratesAndTaxes: 3200,
    },
    specs: {
      bedrooms: 3,
      bathrooms: 2,
      garages: 1,
      carports: 1,
      totalParking: 2,
      erfSize: 600,
      floorSize: 240,
      yearBuilt: 1952,
    },
    features: {
      pool: false,
      garden: true,
      securitySystem: true,
      borehole: false,
      solarPanels: false,
      backupPower: false,
      airConditioning: false,
      furnished: false,
      petFriendly: true,
      wheelchairAccess: false,
      balcony: false,
      fireplace: true,
      staffQuarters: false,
      flatlet: false,
      tennisCourt: false,
      gym: false,
      elevator: false,
    },
    images: [
      {
        id: generateId(),
        url: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?w=200&q=80',
        isPrimary: true,
        order: 0,
        createdAt: new Date().toISOString(),
      },
    ],
    agent: sampleAgent,
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-03-20T15:30:00Z',
    publishedAt: '2026-02-15T11:00:00Z',
    viewCount: 2134,
    inquiryCount: 45,
    favoriteCount: 178,
    syndicatedTo: ['Property24', 'Private Property', 'Gumtree'],
    slug: 'charming-3-bedroom-house-claremont',
    metaTitle: 'Character Home for Sale Claremont | PropAgent',
    metaDescription: 'Beautiful character home with Oregon pine floors, established garden. 3 bed, 2 bath. Near Cavendish. R6.2M.',
    isDraft: false,
  },
  {
    id: generateId(),
    title: 'Industrial Warehouse in Spartan',
    description: 'Prime industrial property suitable for manufacturing or distribution. High volume warehouse with excellent height, ample yard space for trucks, and modern office component. Easy access to N3 highway.',
    listingType: 'sale' as ListingType,
    type: 'industrial' as PropertyType,
    status: 'active' as PropertyStatus,
    location: {
      streetAddress: '67 Spartan Road',
      suburb: 'Spartan',
      city: 'Kempton Park',
      province: 'gauteng' as Province,
      postalCode: '1619',
    },
    pricing: {
      price: 18500000,
      negotiable: true,
      ratesAndTaxes: 18000,
    },
    specs: {
      bedrooms: 0,
      bathrooms: 4,
      garages: 0,
      erfSize: 5000,
      floorSize: 3200,
      yearBuilt: 2015,
    },
    features: {
      pool: false,
      garden: false,
      securitySystem: true,
      borehole: false,
      solarPanels: false,
      backupPower: true,
      airConditioning: true,
      furnished: false,
      petFriendly: false,
      wheelchairAccess: true,
      balcony: false,
      fireplace: false,
      staffQuarters: false,
      flatlet: false,
      tennisCourt: false,
      gym: false,
      elevator: false,
    },
    images: [
      {
        id: generateId(),
        url: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=200&q=80',
        isPrimary: true,
        order: 0,
        createdAt: new Date().toISOString(),
      },
    ],
    agent: sampleAgent,
    createdAt: '2026-03-05T09:30:00Z',
    updatedAt: '2026-04-02T11:45:00Z',
    publishedAt: '2026-03-05T10:00:00Z',
    viewCount: 445,
    inquiryCount: 8,
    favoriteCount: 12,
    syndicatedTo: ['Private Property Commercial'],
    slug: 'industrial-warehouse-spartan-kempton-park',
    metaTitle: 'Industrial Warehouse for Sale Spartan | PropAgent',
    metaDescription: 'Prime industrial property, 3,200m² warehouse, 5,000m² stand. Near N3. Suitable for manufacturing/distribution. R18.5M.',
    isDraft: false,
  },
  {
    id: generateId(),
    title: 'Vacant Land in Plettenberg Bay',
    description: 'Rare opportunity to own a sea-view stand in exclusive Plettenberg Bay estate. Build your dream home on this elevated plot with unobstructed ocean views. Estate includes beach access and 24-hour security.',
    listingType: 'sale' as ListingType,
    type: 'vacant_land' as PropertyType,
    status: 'active' as PropertyStatus,
    location: {
      streetAddress: '12 Whale Rock Ridge',
      suburb: 'Plettenberg Bay',
      city: 'Plettenberg Bay',
      province: 'western_cape' as Province,
      postalCode: '6600',
      complexName: 'Whale Rock Ridge Estate',
    },
    pricing: {
      price: 3200000,
      negotiable: true,
      ratesAndTaxes: 850,
    },
    specs: {
      bedrooms: 0,
      bathrooms: 0,
      garages: 0,
      landSize: 850,
    },
    features: {
      pool: false,
      garden: false,
      securitySystem: true,
      borehole: false,
      solarPanels: false,
      backupPower: false,
      airConditioning: false,
      furnished: false,
      petFriendly: true,
      wheelchairAccess: false,
      balcony: false,
      fireplace: false,
      staffQuarters: false,
      flatlet: false,
      tennisCourt: false,
      gym: false,
      elevator: false,
    },
    images: [
      {
        id: generateId(),
        url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=200&q=80',
        isPrimary: true,
        order: 0,
        createdAt: new Date().toISOString(),
      },
    ],
    agent: sampleAgent,
    createdAt: '2026-03-12T10:15:00Z',
    updatedAt: '2026-04-04T14:00:00Z',
    publishedAt: '2026-03-12T11:00:00Z',
    viewCount: 1567,
    inquiryCount: 22,
    favoriteCount: 89,
    syndicatedTo: ['Property24', 'Private Property'],
    slug: 'vacant-land-plettenberg-bay-sea-view',
    metaTitle: 'Sea View Land for Sale Plettenberg Bay | PropAgent',
    metaDescription: 'Elevated sea-view stand in exclusive estate. 850m², beach access, 24hr security. Build your dream home. R3.2M.',
    isDraft: false,
  },
];

// Sample stats for dashboard
export const samplePropertyStats: PropertyStats = {
  totalListings: 47,
  activeListings: 34,
  draftListings: 5,
  soldListings: 12,
  rentedListings: 8,
  pendingListings: 6,
  totalViews: 45678,
  viewsThisWeek: 3245,
  totalInquiries: 312,
  inquiriesThisWeek: 28,
  averageDaysOnMarket: 42,
};

// Sample recent inquiries
export const sampleRecentInquiries: RecentInquiry[] = [
  {
    id: generateId(),
    propertyId: sampleProperties[0].id,
    propertyTitle: sampleProperties[0].title,
    propertyImage: sampleProperties[0].images[0]?.url,
    inquirerName: 'John Smith',
    inquirerEmail: 'john.smith@email.com',
    inquirerPhone: '+27 71 234 5678',
    message: 'Hi, I\'m very interested in this property. Is it still available? Would it be possible to arrange a viewing for this weekend?',
    status: 'new',
    createdAt: '2026-04-05T14:30:00Z',
  },
  {
    id: generateId(),
    propertyId: sampleProperties[1].id,
    propertyTitle: sampleProperties[1].title,
    propertyImage: sampleProperties[1].images[0]?.url,
    inquirerName: 'Sarah Johnson',
    inquirerEmail: 'sarah.j@example.co.za',
    inquirerPhone: '+27 82 987 6543',
    message: 'Is the price negotiable? I\'m a cash buyer and can close quickly. Also, what are the monthly levies?',
    status: 'contacted',
    createdAt: '2026-04-05T10:15:00Z',
  },
  {
    id: generateId(),
    propertyId: sampleProperties[2].id,
    propertyTitle: sampleProperties[2].title,
    propertyImage: sampleProperties[2].images[0]?.url,
    inquirerName: 'Michael Brown',
    inquirerEmail: 'mbrown@company.com',
    message: 'Good day, I\'d like to schedule a viewing for this townhouse. Are pets allowed in the complex?',
    status: 'viewing_scheduled',
    createdAt: '2026-04-04T16:45:00Z',
  },
  {
    id: generateId(),
    propertyId: sampleProperties[3].id,
    propertyTitle: sampleProperties[3].title,
    propertyImage: sampleProperties[3].images[0]?.url,
    inquirerName: 'Emma Wilson',
    inquirerEmail: 'emma.wilson@gmail.com',
    inquirerPhone: '+27 63 456 7890',
    message: 'Beautiful home! Does the cottage have its own entrance? I\'m looking for a property with potential rental income.',
    status: 'converted',
    createdAt: '2026-04-03T09:20:00Z',
  },
  {
    id: generateId(),
    propertyId: sampleProperties[0].id,
    propertyTitle: sampleProperties[0].title,
    propertyImage: sampleProperties[0].images[0]?.url,
    inquirerName: 'David Thompson',
    inquirerEmail: 'd.thompson@email.co.za',
    message: 'What schools are in the area? We have primary school aged children.',
    status: 'closed',
    createdAt: '2026-04-01T11:30:00Z',
  },
];

// Sample similar properties (for property detail page)
export const getSimilarProperties = (propertyId: string, count: number = 3): Property[] => {
  return sampleProperties
    .filter(p => p.id !== propertyId && p.status === 'active')
    .slice(0, count);
};

// SA Provinces for dropdown
export const saProvinces = [
  { value: 'gauteng', label: 'Gauteng' },
  { value: 'western_cape', label: 'Western Cape' },
  { value: 'kwazulu_natal', label: 'KwaZulu-Natal' },
  { value: 'eastern_cape', label: 'Eastern Cape' },
  { value: 'free_state', label: 'Free State' },
  { value: 'mpumalanga', label: 'Mpumalanga' },
  { value: 'limpopo', label: 'Limpopo' },
  { value: 'north_west', label: 'North West' },
  { value: 'northern_cape', label: 'Northern Cape' },
];

// Property types for dropdown
export const propertyTypes = [
  { value: 'house', label: 'House' },
  { value: 'apartment', label: 'Apartment' },
  { value: 'flat', label: 'Flat' },
  { value: 'townhouse', label: 'Townhouse' },
  { value: 'duplex', label: 'Duplex' },
  { value: 'penthouse', label: 'Penthouse' },
  { value: 'commercial', label: 'Commercial' },
  { value: 'industrial', label: 'Industrial' },
  { value: 'land', label: 'Land' },
  { value: 'vacant_land', label: 'Vacant Land' },
];

// Listing types for dropdown
export const listingTypes = [
  { value: 'sale', label: 'For Sale' },
  { value: 'rent', label: 'To Rent' },
  { value: 'auction', label: 'Auction' },
];

// Property status options
export const propertyStatuses = [
  { value: 'active', label: 'Active', color: 'bg-green-100 text-green-700' },
  { value: 'pending', label: 'Pending', color: 'bg-yellow-100 text-yellow-700' },
  { value: 'sold', label: 'Sold', color: 'bg-blue-100 text-blue-700' },
  { value: 'rented', label: 'Rented', color: 'bg-purple-100 text-purple-700' },
  { value: 'under_offer', label: 'Under Offer', color: 'bg-orange-100 text-orange-700' },
  { value: 'withdrawn', label: 'Withdrawn', color: 'bg-gray-100 text-gray-700' },
  { value: 'draft', label: 'Draft', color: 'bg-stone-100 text-stone-700' },
];

// Feature options for form
export const propertyFeatureOptions = [
  { key: 'pool', label: 'Swimming Pool', icon: 'Waves' },
  { key: 'garden', label: 'Garden', icon: 'TreePine' },
  { key: 'securitySystem', label: 'Security System', icon: 'Shield' },
  { key: 'borehole', label: 'Borehole', icon: 'Droplets' },
  { key: 'solarPanels', label: 'Solar Panels', icon: 'Sun' },
  { key: 'backupPower', label: 'Backup Power', icon: 'Battery' },
  { key: 'airConditioning', label: 'Air Conditioning', icon: 'Wind' },
  { key: 'furnished', label: 'Furnished', icon: 'Sofa' },
  { key: 'petFriendly', label: 'Pet Friendly', icon: 'PawPrint' },
  { key: 'wheelchairAccess', label: 'Wheelchair Access', icon: 'Accessibility' },
  { key: 'balcony', label: 'Balcony', icon: 'SquareStack' },
  { key: 'fireplace', label: 'Fireplace', icon: 'Flame' },
  { key: 'staffQuarters', label: 'Staff Quarters', icon: 'Home' },
  { key: 'flatlet', label: 'Flatlet / Cottage', icon: 'Building' },
  { key: 'tennisCourt', label: 'Tennis Court', icon: 'Circle' },
  { key: 'gym', label: 'Gym', icon: 'Dumbbell' },
  { key: 'elevator', label: 'Elevator', icon: 'ArrowUpDown' },
];
